version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: react_app_db
      POSTGRES_USER: react_app_db_admin
      POSTGRES_PASSWORD: react_app_db_admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
